backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/assets"
collections:
  - name: "actualites" # Used in routes, e.g., /admin/collections/blog
    label: "Actualités" # Used in the UI
    folder: "content/actualites" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Ne pas faire de lien", name: "noLink", widget: "boolean" }
      - { label: "contenu", name: "content", widget: "markdown" }
