---
new_page_extension: md
auto_deploy: false
admin_path: "/admin-crocos"
webhook_url: 
sections:
- type: directory
  path: content/slider
  label: Slider
  create: all
  match: "**/*"
  templates:
  - carousel
- type: heading
  label: Parmètres du site
- type: document
  path: content/general.json
  label: Général
- type: document
  path: content/links.json
  label: menus
upload_dir: static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
