---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Contenu du site
- type: directory
  path: content/slider
  label: Slider
  create: documents
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: content
  label: Pages du site
  create: documents
  match: "*.md"
  templates:
  - page
- type: directory
  path: content/actualites
  label: Actualités
  create: documents
  match: "**/*"
  templates:
  - actualites
- type: directory
  path: content/products
  label: Produits
  create: documents
  match: "**/*"
  templates:
  - products
- type: directory
  path: content/press
  label: Articles de presse
  create: documents
  match: "**/*"
  templates:
  - press
- type: directory
  path: content/places
  label: Points de vente
  create: all
  match: "**/*"
- type: directory
  path: content/team
  label: Equipe
  create: all
  match: "**/*"
  templates:
  - team
- type: heading
  label: Parmètres du site
- type: document
  path: content/general.json
  label: Général
- type: document
  path: content/links.json
  label: menus
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run dev
