---
label: products
hide_body: false
fields:
- name: order
  type: number
  label: Ordre
  description: Le nombre le plus élevé s'affiche en premier
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: title
  type: text
  config:
    required: false
  label: Titre
  description: Le nom du produit
- name: price
  type: number
  label: Prix de vente
  description: Prix du produit TTC
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- name: imageProduct
  type: file
  config:
    maxSize: 64
  label: Image du produit
  description: 'Image du produit (exemple : couverture du livre)'
- name: image
  type: file
  config:
    maxSize: 64
  label: Image principale
  description: Image qui s'affiche en grand (exemple page d'un livre)
- name: images
  type: image_gallery
  config: {}
  label: Gallerie d'images
- name: type
  type: select
  default: livre
  config:
    required: true
    options:
    - livre
    - autre
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type de produit
- name: taxes
  type: select
  default: TVAREDUITE
  config:
    required: true
    options:
    - TVA
    - TVAREDUITE
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Taxes
- name: weight
  type: number
  label: Poids
  description: poids du produit en grammes
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
pages:
- content/products/a-stopover-in-lyon.md
- content/products/cartes-postales.md
- content/products/pack-little-migrating-bird.md
