---
label: products
hide_body: false
fields:
- name: order
  type: number
  label: Ordre
  description: Le nombre le plus élevé s'affiche en premier
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: type
  type: select
  default: livre
  config:
    required: true
    options:
    - livre
    - autre
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type de produit
- name: title
  type: text
  config:
    required: false
  label: Titre
  description: Le nom du produit
- name: price
  type: number
  label: Prix de vente
  description: Prix du produit TTC
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
- name: taxes
  type: select
  default: TVAREDUITE
  config:
    required: true
    options:
    - TVA
    - TVAREDUITE
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Taxes
- name: weight
  type: number
  label: Poids
  description: poids du produit en grammes
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: imageProduct
  type: file
  config:
    maxSize: 64
  label: Image du produit
  description: 'Image du produit (exemple : couverture du livre)'
- name: image
  type: file
  config:
    maxSize: 64
  label: Image principale
  description: Image qui s'affiche en grand (exemple page d'un livre)
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description rapide
  description: Description rapide du produit
- name: images
  type: image_gallery
  config: {}
  label: Gallerie d'images
- name: books_reserved
  type: field_group
  config: {}
  fields:
  - name: pages
    type: number
    label: Nombre de pages
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
  - name: isbn
    type: text
    config:
      required: false
    label: ISBN
  - name: auteur
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: Auteur(s)
  - name: lang
    type: select
    default: ''
    config:
      required: false
      options:
      - fr_FR
      - en_EN
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Langue
  label: Pour les livres
  showOnly:
    field: type
    value: livre
pages:
- content/products/a-stopover-in-lyon.md
- content/products/cartes-postales.md
- content/products/mini-livre.md
